name: Deploy no Kubernetes
on:
    workflow_call:
        inputs:
            manifests:
                type: string
                required: true
                description: "Arquivos manifestos para deploy"
            # images:
            #     type: string
            #     required: true
            #     description: "Imagens que serão alteradas"    
            tag:
                type: string
                required: true
                description: "Imagens que serão alteradas"                   
            environment:                
                type: string
                required: true
                description: "Nome do ambiente que será utilizado"    

jobs:
    CI-CD:
       runs-on: ubuntu-latest
       environment: ${{ inputs.environment }}
       steps: 
       - name: Obtendo o código
         uses: actions/checkout@v4.1.5
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1      
       - name: Login to Amazon ECR
         id: login-ecr
         run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 931783206580.dkr.ecr.us-east-1.amazonaws.com
           
       - name: Build and Push Docker Image to ECR
         uses: docker/build-push-action@v6
         with:
           context: ./src
           file: ./src/Dockerfile
           push: true
           tags: |
             ${{ vars.URL_ECR }}:v${{ github.run_number }}
             ${{ vars.URL_ECR }}:latest  
   
       - name: Configuração de contexto do Kubernetes
         uses: azure/k8s-set-context@v4.0.0
         with:
           method: kubeconfig
           kubeconfig: ${{ secrets.K8S_CONFIG }}
       - name: Execução do Manifesto
         uses: Azure/k8s-deploy@v5
         with:
           manifests: ${{ inputs.manifests}}
           images: ${{ vars.URL_ECR }}:v${{ github.run_number }}   
           namespace: ${{ vars.APP_NAMESPACE }}