name: CI-CD
on: 
  push:
  workflow_dispatch:
jobs:
  CICD-Homolog:
    uses: wallafi01/primeira-pipeline-cicd-ecr/.github/workflows/cidcd.yml@main
    with:
      manifests: |
        k8s/deployment.yaml
      environment: homologacao
    secrets: inherit
  
  Teste-Ambiente:
    needs: [CICD-Homolog]  
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Fake teste
        run: echo "Fake teste ambiente ${{ vars.APP_NAMESPACE }}"

  CICD-Producao:
    needs: [Teste-Ambiente]
    uses: wallafi01/primeira-pipeline-cicd-ecr/.github/workflows/cidcd.yml@main
    with:
      manifests: |
        k8s/deployment.yaml
      environment: producao
    secrets: inherit    

