name: CI-CD
on: 
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.5

  CD-Homolog:
    needs: [CI]
    uses: wallafi01/primeira-pipeline-cicd-ecr/.github/workflows/deploy.yml@main
    with:       
      environment: homologacao
    secrets: inherit
  
  Teste-Ambiente:
    needs: [CD-Homolog]  
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Fake teste
        run: echo "Fake teste ambiente ${{ vars.APP_NAMESPACE }}"

  CICD-Producao:
    needs: [Teste-Ambiente]
    uses: wallafi01/primeira-pipeline-cicd-ecr/.github/workflows/deploy.yml@main
    with:       
      environment: producao
    secrets: inherit    

